
version: 2

sources:
  - name: stocks_db
    database: stocks_db
    schema: main
    description: "The main daily stocks table"

    tables:
      - name: stocks


models:
  - name: stg_daily_stocks
    columns:
      - name: index
        tests:
          - unique
          - not_null
  
  - name: daily_stocks
    columns:
      - name: index
        tests:
          - unique
          - not_null